name:                simdy
version:             0.1.0.0
github:              "githubuser/simdy"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/simdy#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- haskeline
- mtl
- bytestring 
- llvm-hs
- llvm-hs-pretty
- llvm-hs-pure
- containers
- utf8-string
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-missing-signatures

library:
  source-dirs: src

executables:
  simdy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simdy
    - parsec
    - haskeline
    - mtl
    - bytestring 
    - llvm-hs
    - llvm-hs-pretty
    - llvm-hs-pure
    - containers
    - utf8-string
tests:
  simdy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simdy
    - parsec
    - haskeline
    - mtl
    - test-framework
    - test-framework-hunit
    - tasty
    - tasty-hunit
 